import { FaUser } from "react-icons/fa6";
import { FaCertificate } from "react-icons/fa";
import { FaCheck } from "react-icons/fa";
import Image from "next/image";
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Notification',
  description: 'Generated by create next app',
}

export default function Notification() {
  return (
    <div className="flex items-center">

      <div className="hidden md:block md:w-1/3 md:h-screen lg:w-[25%]"></div>

      <div className="mt-[60px] md:mt-[68px] p-2 w-full md:w-2/3 lg:w-[50%]">
        <div className="notification md:px-6">
          <div className="text-green-500 font-bold px-2">Notification</div>

          <div className="bg-white dark:bg-[#3B3B3B] rounded-2xl mt-2">
            <div className="flex gap-2 items-center text-white pt-2 px-2">
              <div className="flex items-center justify-center relative">
                <div className="w-9 h-9 rounded-full overflow-hidden">
                  <Image
                    src="/img/selena-pics.jpg"
                    alt="profile-pics"
                    width={100}
                    height={100}
                    className="w-full h-full object-cover"
                  />
                </div>
                <div className="w-4 h-4 rounded-full absolute bottom-0 -right-1 grid place-content-center bg-blue-500">
                  <FaUser className="text-[8px] text-white" />
                </div>
              </div>
              <div className="flex justify-between w-full items-center pb-1 border-b border-gray-400 border-solid dark:border-gray-500">
                <div>
                  <div className="flex gap-1 items-center">
                    <div className="text-xs font-bold text-black dark:text-white">Selena</div>
                    <span className="relative w-fit"><FaCertificate className="fa fa-certificate text-green-500 text-sm" />
                      <FaCheck className="fa fa-check absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2 text-[6px] font-extrabold text-white dark:text-[#3B3B3B]" />
                    </span>
                  </div>
                  <div className="text-[10px] text-gray-400 dark:text-gray-300">Followed you</div>
                </div>
                <div className="text-[11px] py-1 px-2 rounded-md bg-green-500 text-white dark:text-[#3B3B3B]">Following</div>
              </div>
            </div>

            <div className="flex gap-2 items-center text-white pt-2 px-2">
              <div className="flex items-center justify-center relative">
                <div className="w-9 h-9 rounded-full overflow-hidden">
                  <Image
                    src="/img/victony-profile.jpeg"
                    alt="profile-pics"
                    width={100}
                    height={100}
                    className="w-full h-full object-cover"
                  />
                </div>
                <div className="w-4 h-4 rounded-full absolute bottom-0 -right-1 grid place-content-center bg-blue-500">
                  <FaUser className="text-[8px] text-white" />
                </div>
              </div>
              <div className="flex justify-between w-full items-center pb-1 border-b border-gray-400 border-solid dark:border-gray-500">
                <div>
                  <div className="flex gap-1 items-center">
                    <div className="text-xs font-bold text-black dark:text-white">Victony</div>
                    <span className="relative w-fit"><FaCertificate className="fa fa-certificate text-green-500 text-sm" />
                      <FaCheck className="fa fa-check absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2 text-[6px] font-extrabold text-white dark:text-[#3B3B3B]" />
                    </span>
                  </div>
                  <div className="text-[10px] text-gray-400 dark:text-gray-300">Followed you</div>
                </div>
                <div className="text-[11px] py-1 px-2 rounded-md bg-green-500 text-white dark:text-[#3B3B3B]">Following</div>
              </div>
            </div>

            <div className="flex gap-2 items-center text-white pt-2 px-2">
              <div className="flex items-center justify-center relative">
                <div className="w-9 h-9 rounded-full overflow-hidden">
                  <Image
                    src="/img/mayorkun-profile.jpeg"
                    alt="profile-pics"
                    width={100}
                    height={100}
                    className="w-full h-full object-cover"
                  />
                </div>
                <div className="w-4 h-4 rounded-full absolute bottom-0 -right-1 grid place-content-center bg-blue-500">
                  <FaUser className="text-[8px] text-white" />
                </div>
              </div>
              <div className="flex justify-between w-full items-center pb-1 border-b border-gray-400 border-solid dark:border-gray-500">
                <div>
                  <div className="flex gap-1 items-center">
                    <div className="text-xs font-bold text-black dark:text-white">Mayorkun</div>
                    <span className="relative w text-gray-400-fit"><FaCertificate className="fa fa-certificate text-green-500 text-sm" />
                      <FaCheck className="fa fa-check absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2 text-[6px] font-extrabold text-white dark:text-[#3B3B3B]" />
                    </span>
                  </div>
                  <div className="text-[10px] text-gray-400 dark:text-gray-300">Followed you</div>
                </div>
                <div className="text-[11px] py-1 px-2 rounded-md bg-green-500 text-white dark:text-[#3B3B3B]">Follow</div>
              </div>
            </div>

            <div className="flex gap-2 items-center text-white pt-2 px-2">
              <div className="flex items-center justify-center relative">
                <div className="w-9 h-9 rounded-full overflow-hidden">
                  <Image
                    src="/img/dprince-pics.jpg"
                    alt="profile-pics"
                    width={100}
                    height={100}
                    className="w-full h-full object-cover"
                  />
                </div>
                <div className="w-4 h-4 rounded-full absolute bottom-0 -right-1 grid place-content-center bg-blue-500">
                  <FaUser className="text-[8px] text-white" />
                </div>
              </div>
              <div className="flex justify-between w-full items-center pb-1 border-b border-gray-400 border-solid dark:border-gray-500">
                <div>
                  <div className="flex gap-1 items-center">
                    <div className="text-xs font-bold text-black dark:text-white">D prince</div>
                    <span className="relative w text-gray-400-fit"><FaCertificate className="fa fa-certificate text-green-500 text-sm" />
                      <FaCheck className="fa fa-check absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2 text-[6px] font-extrabold text-white dark:text-[#3B3B3B]" />
                    </span>
                  </div>
                  <div className="text-[10px] text-gray-400 dark:text-gray-300">Followed you</div>
                </div>
                <div className="text-[11px] py-1 px-2 rounded-md bg-green-500 text-white dark:text-[#3B3B3B]">Following</div>
              </div>
            </div>

            <div className="flex gap-2 items-center text-white pt-2 px-2">
              <div className="flex items-center justify-center relative">
                <div className="w-9 h-9 rounded-full overflow-hidden">
                  <Image
                    src="/img/omahlay-profile.jpeg"
                    alt="profile-pics"
                    width={100}
                    height={100}
                    className="w-full h-full object-cover"
                  />
                </div>
                <div className="w-4 h-4 rounded-full absolute bottom-0 -right-1 grid place-content-center bg-blue-500">
                  <FaUser className="text-[8px] text-white" />
                </div>
              </div>
              <div className="flex justify-between w-full items-center pb-1 border-b border-gray-400 border-solid dark:border-gray-500">
                <div>
                  <div className="flex gap-1 items-center">
                    <div className="text-xs font-bold text-black dark:text-white">Omah_lay</div>
                    <span className="relative w text-gray-400-fit"><FaCertificate className="fa fa-certificate text-green-500 text-sm" />
                      <FaCheck className="fa fa-check absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2 text-[6px] font-extrabold text-white dark:text-[#3B3B3B]" />
                    </span>
                  </div>
                  <div className="text-[10px] text-gray-400 dark:text-gray-300">Followed you</div>
                </div>
                <div className="text-[11px] py-1 px-2 rounded-md bg-green-500 text-white dark:text-[#3B3B3B]">Following</div>
              </div>
            </div>

            <div className="flex gap-2 items-center text-white pt-2 px-2">
              <div className="flex items-center justify-center relative">
                <div className="w-9 h-9 rounded-full overflow-hidden">
                  <Image
                    src="/img/joeboy-profile.jpeg"
                    alt="profile-pics"
                    width={100}
                    height={100}
                    className="w-full h-full object-cover"
                  />
                </div>
                <div className="w-4 h-4 rounded-full absolute bottom-0 -right-1 grid place-content-center bg-blue-500">
                  <FaUser className="text-[8px] text-white" />
                </div>
              </div>
              <div className="flex justify-between w-full items-center pb-1 border-b border-gray-400 border-solid dark:border-gray-500">
                <div>
                  <div className="flex gap-1 items-center">
                    <div className="text-xs font-bold text-black dark:text-white">Joeboy</div>
                    <span className="relative w text-gray-400-fit"><FaCertificate className="fa fa-certificate text-green-500 text-sm" />
                      <FaCheck className="fa fa-check absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2 text-[6px] font-extrabold text-white dark:text-[#3B3B3B]" />
                    </span>
                  </div>
                  <div className="text-[10px] text-gray-400 dark:text-gray-300">Followed you</div>
                </div>
                <div className="text-[11px] py-1 px-2 rounded-md bg-green-500 text-white dark:text-[#3B3B3B]">Follow</div>
              </div>
            </div>

            <div className="flex gap-2 items-center text-white pt-2 px-2">
              <div className="flex items-center justify-center relative">
                <div className="w-9 h-9 rounded-full overflow-hidden">
                  <Image
                    src="/img/runda-profile.jpeg"
                    alt="profile-pics"
                    width={100}
                    height={100}
                    className="w-full h-full object-cover"
                  />
                </div>
                <div className="w-4 h-4 rounded-full absolute bottom-0 -right-1 grid place-content-center bg-blue-500">
                  <FaUser className="text-[8px] text-white" />
                </div>
              </div>
              <div className="flex justify-between w-full items-center pb-1 border-b border-gray-400 border-solid dark:border-gray-500">
                <div>
                  <div className="text-xs font-bold text-black dark:text-white">Runda</div>
                  <div className="text-[10px] text-gray-400 dark:text-gray-300">Followed you</div>
                </div>
                <div className="text-[11px] py-1 px-2 rounded-md bg-green-500 text-white dark:text-[#3B3B3B]">Follow</div>
              </div>
            </div>

            <div className="flex gap-2 items-center text-white pt-2 px-2">
              <div className="flex items-center justify-center relative">
                <div className="w-9 h-9 rounded-full overflow-hidden">
                  <Image
                    src="/img/bnxn-profile.jpeg"
                    alt="profile-pics"
                    width={100}
                    height={100}
                    className="w-full h-full object-cover"
                  />
                </div>
                <div className="w-4 h-4 rounded-full absolute bottom-0 -right-1 grid place-content-center bg-blue-500">
                  <FaUser className="text-[8px] text-white" />
                </div>
              </div>
              <div className="flex justify-between w-full items-center pb-1 border-b border-gray-400 border-solid dark:border-gray-500">
                <div>
                  <div className="flex gap-1 items-center">
                    <div className="text-xs font-bold text-black dark:text-white">Bnxn</div>
                    <span className="relative w text-gray-400-fit"><FaCertificate className="fa fa-certificate text-green-500 text-sm" />
                      <FaCheck className="fa fa-check absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2 text-[6px] font-extrabold text-white dark:text-[#3B3B3B]" />
                    </span>
                  </div>
                  <div className="text-[10px] text-gray-400 dark:text-gray-300">Followed you</div>
                </div>
                <div className="text-[11px] py-1 px-2 rounded-md bg-green-500 text-white dark:text-[#3B3B3B]">Following</div>
              </div>
            </div>

            <div className="flex gap-2 items-center text-white pt-2 px-2">
              <div className="flex items-center justify-center relative">
                <div className="w-9 h-9 rounded-full overflow-hidden">
                  <Image
                    src="/img/fireboy-profile.jpeg"
                    alt="profile-pics"
                    width={100}
                    height={100}
                    className="w-full h-full object-cover"
                  />
                </div>
                <div className="w-4 h-4 rounded-full absolute bottom-0 -right-1 grid place-content-center bg-blue-500">
                  <FaUser className="text-[8px] text-white" />
                </div>
              </div>
              <div className="flex justify-between w-full items-center pb-1 border-b border-gray-400 border-solid dark:border-gray-500">
                <div>
                  <div className="flex gap-1 items-center">
                    <div className="text-xs font-bold text-black dark:text-white">Fireboy</div>
                    <span className="relative w text-gray-400-fit"><FaCertificate className="fa fa-certificate text-green-500 text-sm" />
                      <FaCheck className="fa fa-check absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2 text-[6px] font-extrabold text-white dark:text-[#3B3B3B]" />
                    </span>
                  </div>
                  <div className="text-[10px] text-gray-400 dark:text-gray-300">Followed you</div>
                </div>
                <div className="text-[11px] py-1 px-2 rounded-md bg-green-500 text-white dark:text-[#3B3B3B]">Following</div>
              </div>
            </div>

            <div className="flex gap-2 items-center text-white pt-2 px-2">
              <div className="flex items-center justify-center relative">
                <div className="w-9 h-9 rounded-full overflow-hidden">
                  <Image
                    src="/img/lasmid-profile.jpeg"
                    alt="profile-pics"
                    width={100}
                    height={100}
                    className="w-full h-full object-cover"
                  />
                </div>
                <div className="w-4 h-4 rounded-full absolute bottom-0 -right-1 grid place-content-center bg-blue-500">
                  <FaUser className="text-[8px] text-white" />
                </div>
              </div>
              <div className="flex justify-between w-full items-center pb-1 border-b border-gray-400 border-solid dark:border-gray-500">
                <div>
                  <div className="text-xs font-bold text-black dark:text-white">Lasmid</div>
                  <div className="text-[10px] text-gray-400 dark:text-gray-300">Followed you</div>
                </div>
                <div className="text-[11px] py-1 px-2 rounded-md bg-green-500 text-white dark:text-[#3B3B3B]">Follow</div>
              </div>
            </div>

            <div className="flex gap-2 items-center text-white p-2">
              <div className="flex items-center justify-center relative">
                <div className="w-9 h-9 rounded-full overflow-hidden">
                  <Image
                    src="/img/ruger-profile.jpeg"
                    alt="profile-pics"
                    width={100}
                    height={100}
                    className="w-full h-full object-cover"
                  />
                </div>
                <div className="w-4 h-4 rounded-full absolute bottom-0 -right-1 grid place-content-center bg-blue-500">
                  <FaUser className="text-[8px] text-white" />
                </div>
              </div>
              <div className="flex justify-between w-full items-center pb-1">
                <div>
                  <div className="flex gap-1 items-center">
                    <div className="text-xs font-bold text-black dark:text-white">Ruger</div>
                    <span className="relative w-fit"><FaCertificate className="fa fa-certificate text-green-500 text-sm" />
                      <FaCheck className="fa fa-check absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2 text-[6px] font-extrabold text-white dark:text-[#3B3B3B]" />
                    </span>
                  </div>
                  <div className="text-[10px] text-gray-400 dark:text-gray-300">Followed you</div>
                </div>
                <div className="text-[11px] py-1 px-2 rounded-md bg-green-500 text-white dark:text-[#3B3B3B]">Following</div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="hidden lg:block lg:w-[25%] lg:h-screen"></div>
    </div>
  )
}