import { FaSearch } from "react-icons/fa";
import { IoEyeSharp } from "react-icons/io5";
import { FaCertificate } from "react-icons/fa";
import { FaCheck } from "react-icons/fa";
import Image from "next/image";
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Explore',
  description: 'Generated by create next app',
}

export default function Explore() {
  return (
    <div className="flex items-center">

      <div className="hidden md:block md:w-1/3 md:h-screen lg:w-[25%]"></div>

      <div className="mt-[60px] md:mt-[68px] px-2 pt-4 pb-2 w-full md:w-2/3 lg:w-[50%]">
        <div className="searchbar md:px-16">
          <form>
            <div className="relative flex items-center text-gray-400 focus-within:text-gray-700">
              <FaSearch className="absolute ml-3 pointer-events-none" />
              <input type="text" name="search" placeholder="Search..." autoComplete="off" aria-label="Search..."
                className="w-full pr-3 pl-10 py-2 font-semibold text-black rounded-full outline-green-500" />
            </div>
          </form>
        </div>

        <div className="font-bold text-green-500 w-fit mx-auto mt-2">Trending</div>

        <div className="card mt-2 md:px-6">
          <div className="grid grid-cols-2 sm-screen1 md:grid-cols-3 px-2 gap-3">
            <div className="h-56 rounded-xl bg-[url('/img/oxlade-gif.gif')]">
              <div className="flex items-end h-full pb-1 pl-1">
                <div className="flex gap-2 items-center text-white p-2">
                  <div className="w-9 h-9 rounded-full overflow-hidden">
                    <Image
                      src="/img/oxlade-profile.jpeg"
                      alt="profile-pics"
                      width={100}
                      height={100}
                      className="w-full h-full object-cover"
                    />
                  </div>
                  <div>
                    <div className="flex gap-1 items-center">
                      <div className="text-xs font-bold">Oxlade</div>
                      <span className="relative w-fit"><FaCertificate className="fa fa-certificate text-green-500 text-sm" />
                        <FaCheck className="fa fa-check absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2 text-[6px] font-extrabold text-black" />
                      </span>
                    </div>
                    <div className="text-[10px]"><IoEyeSharp className="mr-1 inline-block" />6.2k views</div>
                  </div>
                </div>
              </div>
            </div>
            <div className="h-56 rounded-xl bg-[url('/img/selena-gif.gif')]">
              <div className="flex items-end h-full pb-1 pl-1">
                <div className="flex gap-2 items-center text-white p-2">
                  <div className="w-9 h-9 rounded-full overflow-hidden">
                    <Image
                      src="/img/selena-pics.jpg"
                      alt="profile-pics"
                      width={100}
                      height={100}
                      className="w-full h-full object-cover"
                    />
                  </div>
                  <div>
                    <div className="flex gap-1 items-center">
                      <div className="text-xs font-bold">Selena</div>
                      <span className="relative w-fit"><FaCertificate className="fa fa-certificate text-green-500 text-sm" />
                        <FaCheck className="fa fa-check absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2 text-[6px] font-extrabold text-black" />
                      </span>
                    </div>
                    <div className="text-[10px]"><IoEyeSharp className="mr-1 inline-block" />7k views</div>
                  </div>
                </div>
              </div>
            </div>
            <div className="h-56 rounded-xl bg-[url('/img/lasmid-gif.webp')]">
              <div className="flex items-end h-full pb-1 pl-1">
                <div className="flex gap-2 items-center text-white p-2">
                  <div className="w-9 h-9 rounded-full overflow-hidden">
                    <Image
                      src="/img/lasmid-profile.jpeg"
                      alt="profile-pics"
                      width={100}
                      height={100}
                      className="w-full h-full object-cover"
                    />
                  </div>
                  <div>
                    <div className="text-sm font-bold">Lasmid</div>
                    <div className="text-[10px]"><IoEyeSharp className="mr-1 inline-block" />2.9k views</div>
                  </div>
                </div>
              </div>
            </div>
            <div className="h-56 rounded-xl bg-[url('/img/joeboy-gif.gif')]">
              <div className="flex items-end h-full pb-1 pl-1">
                <div className="flex gap-2 items-center text-white p-2">
                  <div className="w-9 h-9 rounded-full overflow-hidden">
                    <Image
                      src="/img/joeboy-profile.jpeg"
                      alt="profile-pics"
                      width={100}
                      height={100}
                      className="w-full h-full object-cover"
                    />
                  </div>
                  <div>
                    <div className="flex gap-1 items-center">
                      <div className="text-xs font-bold">Joeboy</div>
                      <span className="relative w-fit"><FaCertificate className="fa fa-certificate text-green-500 text-sm" />
                        <FaCheck className="fa fa-check absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2 text-[6px] font-extrabold text-black" />
                      </span>
                    </div>
                    <div className="text-[10px]"><IoEyeSharp className="mr-1 inline-block" />5.1k views</div>
                  </div>
                </div>
              </div>
            </div>
            <div className="h-56 rounded-xl bg-[url('/img/rema-gif.gif')]">
              <div className="flex items-end h-full pb-1 pl-1">
                <div className="flex gap-2 items-center text-white p-2">
                  <div className="w-9 h-9 rounded-full overflow-hidden">
                    <Image
                      src="/img/rema-profile.jpeg"
                      alt="profile-pics"
                      width={100}
                      height={100}
                      className="w-full h-full object-cover"
                    />
                  </div>
                  <div>
                    <div className="flex gap-1 items-center">
                      <div className="text-xs font-bold">Rema</div>
                      <span className="relative w-fit"><FaCertificate className="fa fa-certificate text-green-500 text-sm" />
                        <FaCheck className="fa fa-check absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2 text-[6px] font-extrabold text-black" />
                      </span>
                    </div>
                    <div className="text-[10px]"><IoEyeSharp className="mr-1 inline-block" />9k views</div>
                  </div>
                </div>
              </div>
            </div>
            <div className="h-56 rounded-xl bg-[url('/img/omahlay-gif.webp')]">
              <div className="flex items-end h-full pb-1 pl-1">
                <div className="flex gap-2 items-center text-white p-2">
                  <div className="w-9 h-9 rounded-full overflow-hidden">
                    <Image
                      src="/img/omahlay-profile.jpeg"
                      alt="profile-pics"
                      width={100}
                      height={100}
                      className="w-full h-full object-cover"
                    />
                  </div>
                  <div>
                    <div className="flex gap-1 items-center">
                      <div className="text-xs font-bold">Omah_lay</div>
                      <span className="relative w-fit"><FaCertificate className="fa fa-certificate text-green-500 text-sm" />
                        <FaCheck className="fa fa-check absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2 text-[6px] font-extrabold text-black" />
                      </span>
                    </div>
                    <div className="text-[10px]"><IoEyeSharp className="mr-1 inline-block" />3.8k views</div>
                  </div>
                </div>
              </div>
            </div>
            <div className="h-56 rounded-xl bg-[url('/img/fireboy-gif.gif')]">
              <div className="flex items-end h-full pb-1 pl-1">
                <div className="flex gap-2 items-center text-white p-2">
                  <div className="w-9 h-9 rounded-full overflow-hidden">
                    <Image
                      src="/img/fireboy-profile.jpeg"
                      alt="profile-pics"
                      width={100}
                      height={100}
                      className="w-full h-full object-cover"
                    />
                  </div>
                  <div>
                    <div className="flex gap-1 items-center">
                      <div className="text-xs font-bold">Fireboy</div>
                      <span className="relative w-fit"><FaCertificate className="fa fa-certificate text-green-500 text-sm" />
                        <FaCheck className="fa fa-check absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2 text-[6px] font-extrabold text-black" />
                      </span>
                    </div>
                    <div className="text-[10px]"><IoEyeSharp className="mr-1 inline-block" />8.3k views</div>
                  </div>
                </div>
              </div>
            </div>
            <div className="h-56 rounded-xl bg-[url('/img/ruger-gif.webp')]">
              <div className="flex items-end h-full pb-1 pl-1 bg-ruger">
                <div className="flex gap-2 items-center text-white p-2">
                  <div className="w-9 h-9 rounded-full overflow-hidden">
                    <Image
                      src="/img/ruger-profile.jpeg"
                      alt="profile-pics"
                      width={100}
                      height={100}
                      className="w-full h-full object-cover"
                    />
                  </div>
                  <div>
                    <div className="flex gap-1 items-center">
                      <div className="text-xs font-bold">Ruger</div>
                      <span className="relative w-fit"><FaCertificate className="fa fa-certificate text-green-500 text-sm" />
                        <FaCheck className="fa fa-check absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2 text-[6px] font-extrabold text-black" />
                      </span>
                    </div>
                    <div className="text-[10px]"><IoEyeSharp className="mr-1 inline-block" />4.5k views</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="hidden lg:block lg:w-[25%] lg:h-screen"></div>
    </div>
  )
}