import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Bookmark',
    description: 'Generated by create next app',
}

export default function Bookmark() {
  return (
    <div className="flex items-center">

    <div className="hidden md:block md:w-1/3 md:h-screen lg:w-[25%]"></div>

    <div className="p-2 w-full h-screen md:w-2/3 lg:w-[50%]">
      <div className="h-full w-full grid place-content-center text-2xl text-green-500 font-agbalumo">No Bookmark Yet</div>
    </div>

    <div className="hidden lg:block lg:w-[25%] lg:h-screen"></div>
  </div>
  )
}