import { FaChevronRight } from "react-icons/fa";
import { FaChartBar } from "react-icons/fa";
import { FaCreditCard } from "react-icons/fa";
import { FaRegBell } from "react-icons/fa";
import { MdLockOutline } from "react-icons/md";
import { FaUniversalAccess } from "react-icons/fa6";
import { MdOutlineAccountCircle } from "react-icons/md";
import { FaLanguage } from "react-icons/fa6";
import { FaRegLifeRing } from "react-icons/fa";
import { FaInfoCircle } from "react-icons/fa";
import { PiUserSwitchBold } from "react-icons/pi";
import { FiLogOut } from "react-icons/fi";
import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Setting',
    description: 'Generated by create next app',
}

export default function Setting() {
  return (
    <div className="flex items-center">

    <div className="hidden md:block md:w-1/3 md:h-screen lg:w-[25%]"></div>

    <div className="mt-[60px] md:px-6 p-2 w-full md:w-2/3 lg:w-[50%]">
      <div className="w-full h-60 grid place-content-center">
        <div className="text-green-500 text-center font-bold text-2xl">Setting</div>
      </div>
      <div className="bg-white dark:bg-[#3B3B3B] dark:text-white rounded-2xl text-black">
        <div className="flex gap-2 items-center px-2 pt-3">
          <div className="w-9 h-9 flex items-center">
            <FaChartBar/>
          </div>
          <div className="flex justify-between w-full items-center pb-3 border-b border-gray-400 border-solid dark:border-gray-500">
            <div>
              <div className="text-xs font-bold">Data usage</div>
            </div>
            <div><FaChevronRight className="text-xs"/></div>
          </div>
        </div>

        <div className="flex gap-2 items-center pt-1 px-2">
          <div className="w-9 h-9 flex items-center">
            <FaCreditCard/>
          </div>
          <div className="flex justify-between w-full items-center pb-3 border-b border-gray-400 border-solid dark:border-gray-500">
            <div>
              <div className="text-xs font-bold">Payments</div>
            </div>
            <div><FaChevronRight className="text-xs"/></div>
          </div>
        </div>

        <div className="flex gap-2 items-center pt-1 px-2">
          <div className="w-9 h-9 flex items-center">
            <FaRegBell/>
          </div>
          <div className="flex justify-between w-full items-center pb-3 border-b border-gray-400 border-solid dark:border-gray-500">
            <div>
              <div className="text-xs font-bold">Notifications</div>
            </div>
            <div><FaChevronRight className="text-xs"/></div>
          </div>
        </div>

        <div className="flex gap-2 items-center pt-1 px-2">
          <div className="w-9 h-9 flex items-center">
            <MdLockOutline/>
          </div>
          <div className="flex justify-between w-full items-center pb-3 border-b border-gray-400 border-solid dark:border-gray-500">
            <div>
              <div className="text-xs font-bold">Privacy</div>
            </div>
            <div><FaChevronRight className="text-xs"/></div>
          </div>
        </div>

        <div className="flex gap-2 items-center pt-1 px-2">
          <div className="w-9 h-9 flex items-center">
            <FaUniversalAccess/>
          </div>
          <div className="flex justify-between w-full items-center pb-3 border-b border-gray-400 border-solid dark:border-gray-500">
            <div>
              <div className="text-xs font-bold">Accessibility</div>
            </div>
            <div><FaChevronRight className="text-xs"/></div>
          </div>
        </div>

        <div className="flex gap-2 items-center pt-1 px-2">
          <div className="w-9 h-9 flex items-center">
            <MdOutlineAccountCircle/>
          </div>
          <div className="flex justify-between w-full items-center pb-3 border-b border-gray-400 border-solid dark:border-gray-500">
            <div>
              <div className="text-xs font-bold">Account</div>
            </div>
            <div><FaChevronRight className="text-xs"/></div>
          </div>
        </div>

        <div className="flex gap-2 items-center pt-1 px-2">
          <div className="w-9 h-9 flex items-center">
            <FaLanguage/>
          </div>
          <div className="flex justify-between w-full items-center pb-3 border-b border-gray-400 border-solid dark:border-gray-500">
            <div>
              <div className="text-xs font-bold">Language</div>
            </div>
            <div><FaChevronRight className="text-xs"/></div>
          </div>
        </div>

        <div className="flex gap-2 items-center pt-1 px-2">
          <div className="w-9 h-9 flex items-center">
            <FaRegLifeRing/>
          </div>
          <div className="flex justify-between w-full items-center pb-3 border-b border-gray-400 border-solid dark:border-gray-500">
            <div>
              <div className="text-xs font-bold">Help</div>
            </div>
            <div><FaChevronRight className="text-xs"/></div>
          </div>
        </div>

        <div className="flex gap-2 items-center pt-1 px-2">
          <div className="w-9 h-9 flex items-center">
            <FaInfoCircle/>
          </div>
          <div className="flex justify-between w-full items-center pb-3 border-b border-gray-400 border-solid dark:border-gray-500">
            <div>
              <div className="text-xs font-bold">About</div>
            </div>
            <div><FaChevronRight className="text-xs"/></div>
          </div>
        </div>

        <div className="flex gap-2 items-center pt-1 px-2">
          <div className="w-9 h-9 flex items-center">
            <PiUserSwitchBold/>
          </div>
          <div className="flex justify-between w-full items-center pb-3 border-b border-gray-400 border-solid dark:border-gray-500">
            <div>
              <div className="text-xs font-bold">Switch profiles</div>
            </div>
            <div><FaChevronRight className="text-xs"/></div>
          </div>
        </div>

        <div className="flex gap-2 items-center pt-1 px-2">
          <div className="w-9 h-9 flex items-center">
            <FiLogOut/>
          </div>
          <div className="flex justify-between w-full items-center pb-3">
            <div>
              <div className="text-xs font-bold">Log out</div>
            </div>
            <div><FaChevronRight className="text-xs"/></div>
          </div>
        </div>
      </div>
    </div>

    <div className="hidden lg:block lg:w-[25%] lg:h-screen"></div>
  </div>
  )
}