import { FaRegBookmark } from "react-icons/fa";
import { FaRegHeart } from "react-icons/fa";
import { BiCommentDetail } from "react-icons/bi";
import { FaShareAlt } from "react-icons/fa";
import { FaPlus } from "react-icons/fa";
import { FaCertificate } from "react-icons/fa";
import { FaCheck } from "react-icons/fa";
import { FaEllipsisH } from "react-icons/fa";
import { FaUser } from "react-icons/fa";
import Image from 'next/image';

import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Zizou App',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <main className="flex items-center">

      <div className="hidden md:block md:w-1/3 md:h-screen lg:w-[25%]"></div>

      <div className="mt-[60px] md:mt-[68px] lg:mt-[72px] w-full md:w-2/3 lg:w-[50%] pb-2">
        <div className="stories">
          <div className="text-green-500 font-bold pl-2 md:ml-2 md:px-4">Stories</div>
          <div className="flex gap-3 overflow-x-auto md:pt-2 pb-2 scrollbar border-b border-gray-400 border-solid dark:border-gray-500">
            <div className="md:px-4 flex gap-3">
              <div className="pl-2">
                <div className="flex items-center justify-center relative">
                  <div className="w-12 h-12 rounded-full overflow-hidden">
                    <Image
                      src="/img/star-profile.jpeg"
                      alt="profile-pics"
                      width={100}
                      height={100}
                      className="w-full h-full object-cover"
                    />
                  </div>
                  <div className="w-3 h-3 rounded-full absolute bottom-0 right-0 grid place-content-center bg-blue-500">
                    <FaPlus className="fa fa-plus text-[8px] text-white" />
                  </div>
                </div>
                <div className="text-center text-[10px] mt-1 text-black dark:text-gray-300">Create</div>
              </div>
              <div>
                <div className="flex items-center justify-center">
                  <div className="w-12 h-12 border-2 border-green-500 rounded-full overflow-hidden">
                    <Image
                      src="/img/rema-profile.jpeg"
                      alt="profile-pics"
                      width={100}
                      height={100}
                      className="w-full h-full object-cover"
                    />
                  </div>
                </div>
                <div className="text-center text-[10px] mt-1 text-black dark:text-gray-300">Rema</div>
              </div>
              <div>
                <div className="flex items-center justify-center">
                  <div className="w-12 h-12 rounded-full overflow-hidden">
                    <Image
                      src="/img/fireboy-profile.jpeg"
                      alt="profile-pics"
                      width={100}
                      height={100}
                      className="w-full h-full object-cover"
                    />
                  </div>
                </div>
                <div className="text-center text-[10px] mt-1 text-black dark:text-gray-300">Fireboy</div>
              </div>
              <div>
                <div className="flex items-center justify-center">
                  <div className="w-12 h-12 rounded-full overflow-hidden">
                    <Image
                      src="/img/bnxn-profile.jpeg"
                      alt="profile-pics"
                      width={100}
                      height={100}
                      className="w-full h-full object-cover"
                    />
                  </div>
                </div>
                <div className="text-center text-[10px] mt-1 text-black dark:text-gray-300">Bnxn</div>
              </div>
              <div>
                <div className="flex items-center justify-center">
                  <div className="w-12 h-12 border-2 border-green-500 rounded-full overflow-hidden">
                    <Image
                      src="/img/victony-profile.jpeg"
                      alt="profile-pics"
                      width={100}
                      height={100}
                      className="w-full h-full object-cover"
                    />
                  </div>
                </div>
                <div className="text-center text-[10px] mt-1 text-black dark:text-gray-300">Victony</div>
              </div>
              <div>
                <div className="flex items-center justify-center">
                  <div className="w-12 h-12 border-2 border-green-500 rounded-full overflow-hidden">
                    <Image
                      src="/img/ruger-profile.jpeg"
                      alt="profile-pics"
                      width={100}
                      height={100}
                      className="w-full h-full object-cover"
                    />
                  </div>
                </div>
                <div className="text-center text-[10px] mt-1 text-black dark:text-gray-300">Ruger</div>
              </div>
              <div>
                <div className="flex items-center justify-center">
                  <div className="w-12 h-12 rounded-full overflow-hidden">
                    <Image
                      src="/img/omahlay-profile.jpeg"
                      alt="profile-pics"
                      width={100}
                      height={100}
                      className="w-full h-full object-cover"
                    />
                  </div>
                </div>
                <div className="text-center text-[10px] mt-1 text-black dark:text-gray-300">Omah_lay</div>
              </div>
              <div>
                <div className="flex items-center justify-center">
                  <div className="w-12 h-12 border-2 border-green-500 rounded-full overflow-hidden">
                    <Image
                      src="/img/oxlade-profile.jpeg"
                      alt="profile-pics"
                      width={100}
                      height={100}
                      className="w-full h-full object-cover"
                    />
                  </div>
                </div>
                <div className="text-center text-[10px] mt-1 text-black dark:text-gray-300">Oxlade</div>
              </div>
            </div>
          </div>
        </div>

        <div className="post mt-4 pb-4 px-2 md:px-6 border-b border-gray-400 border-solid dark:border-gray-500">
          <div className="w-full rounded-lg p-2 bg-white dark:bg-[#3B3B3B]">
            <div className="post-head flex justify-between">
              <div className="flex gap-2 cursor-pointer items-center">
                <div className="flex items-center justify-center">
                  <div className="w-8 h-8 rounded-full overflow-hidden">
                    <Image
                      src="/img/rema-profile.jpeg"
                      alt="profile-pics"
                      width={100}
                      height={100}
                      className="w-full h-full object-cover"
                    />
                  </div>
                </div>
                <div>
                  <div className="flex gap-1 items-center">
                    <div className="text-xs font-bold text-black dark:text-white">Rema</div>
                    <span className="relative w-fit"><FaCertificate className="fa fa-certificate text-green-500 text-sm" />
                      <FaCheck className="fa fa-check absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2 text-[6px] font-extrabold text-white dark:text-[#3B3B3B]" />
                    </span>
                  </div>
                  <div className="text-[8px] text-gray-400 dark:text-gray-300">ATLANTA, 42 MINUTES AGO</div>
                </div>
              </div>
              <div className="cursor-pointer text-black dark:text-white">
                <FaEllipsisH />
              </div>
            </div>

            <div className="post-img mt-[6px]">
              <div className="w-full h-44 rounded-lg overflow-hidden">
                <Image
                  src="/img/rema-post.jpeg"
                  alt="post-img"
                  width={500}
                  height={500}
                  className="w-full h-full"
                />
              </div>
            </div>

            <div className="post-icons flex justify-between text-black dark:text-white mt-2 px-2">
              <div className="flex items-end gap-2">
                <FaRegHeart />
                <BiCommentDetail />
                <FaShareAlt />
              </div>
              <div>
                <FaRegBookmark />
              </div>
            </div>

            <div className="liked-by mt-2 flex gap-1 items-center">
              <div className="flex">
                <span>
                  <div className="flex items-center justify-center">
                    <div className="w-5 h-5 border-2 border-white rounded-full overflow-hidden dark:border-[#3B3B3B]">
                      <Image
                        src="/img/victony-profile.jpeg"
                        alt="profile-pics"
                        width={100}
                        height={100}
                        className="w-full h-full object-cover"
                      />
                    </div>
                  </div>
                </span>
                <span className="ml-[-0.6rem]">
                  <div className="flex items-center justify-center">
                    <div className="w-5 h-5 border-2 border-white rounded-full overflow-hidden dark:border-[#3B3B3B]">
                      <Image
                        src="/img/ruger-profile.jpeg"
                        alt="profile-pics"
                        width={100}
                        height={100}
                        className="w-full h-full object-cover"
                      />
                    </div>
                  </div>
                </span>
                <span className="ml-[-0.6rem]">
                  <div className="flex items-center justify-center">
                    <div className="w-5 h-5 border-2 border-white rounded-full overflow-hidden dark:border-[#3B3B3B]">
                      <Image
                        src="/img/selena-pics.jpg"
                        alt="profile-pics"
                        width={100}
                        height={100}
                        className="w-full h-full object-cover"
                      />
                    </div>
                  </div>
                </span>
              </div>
              <div>
                <p className="text-[10px] text-black dark:text-white">Liked by <span className="font-bold">Selena Gomez</span> and <span
                  className="font-bold">504,038 others</span></p>
              </div>
            </div>

            <div className="comments text-[10px]">
              <p className="text-black dark:text-white"><span className="font-bold">Rema</span> I thank Jehovah #GodBlessAfroBeatz</p>
              <p className="text-gray-400 dark:text-gray-300">View all 33,385 comments</p>
            </div>
          </div>
        </div>

        <div className="followers pl-2 pb-4 md:pl-6 border-b border-gray-400 border-solid dark:border-gray-500">
          <div className="text-green-500 font-bold pl-2 py-2">Who to follow</div>
          <div className="flex gap-3 overflow-x-auto scrollbar">
            <div className="w-32 h-52 bg-white dark:bg-[#3B3B3B] rounded-lg">
              <div className="px-6">
                <div className="flex items-center justify-center pt-4 pb-2">
                  <div className="w-20 h-20 rounded-full overflow-hidden">
                    <Image
                      src="/img/mayorkun-profile.jpeg"
                      alt="profile-pics"
                      width={100}
                      height={100}
                      className="w-full h-full object-cover"
                    />
                  </div>
                </div>
                <div className="w-fit mx-auto flex gap-1 items-center">
                  <div className="text-sm font-bold text-black dark:text-white">Mayorkun</div>
                  <span className="relative w-fit"><FaCertificate className="fa fa-certificate text-green-500 text-sm" />
                    <FaCheck className="fa fa-check absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2 text-[6px] font-extrabold text-white dark:text-[#3B3B3B]" />
                  </span>
                </div>
                <div className="mt-2 flex justify-center">
                  <button
                    className="bg-green-500 text-white font-semibold py-2 px-4 rounded-full text-sm mx-auto">Follow</button>
                </div>
              </div>
              <div className="text-[9px] flex gap-1 items-center mt-2 pl-3 pr-2 text-gray-400 dark:text-gray-300">
                <FaUser className="self-start" />
                <p className="self-start">Crayon and 100 others follow</p>
              </div>
            </div>

            <div className="w-32 h-52 bg-white dark:bg-[#3B3B3B] rounded-lg">
              <div className="px-6">
                <div className="flex items-center justify-center pt-4 pb-2">
                  <div className="w-20 h-20 rounded-full overflow-hidden">
                    <Image
                      src="/img/runda-profile.jpeg"
                      alt="profile-pics"
                      width={100}
                      height={100}
                      className="w-full h-full object-cover"
                    />
                  </div>
                </div>
                <div className="w-fit mx-auto">
                  <div className="text-sm font-bold text-black dark:text-white">Runda</div>
                </div>
                <div className="mt-2 flex justify-center">
                  <button
                    className="bg-green-500 text-white font-semibold py-2 px-4 rounded-full text-sm mx-auto">Follow</button>
                </div>
              </div>
              <div className="text-[9px] flex gap-1 items-center mt-2 pl-3 pr-2 text-gray-400 dark:text-gray-300">
                <FaUser className="self-start" />
                <p className="self-start">Tyla and 47 others follow</p>
              </div>
            </div>

            <div className="w-32 h-52 bg-white dark:bg-[#3B3B3B] rounded-lg">
              <div className="px-6">
                <div className="flex items-center justify-center pt-4 pb-2">
                  <div className="w-20 h-20 rounded-full overflow-hidden">
                    <Image
                      src="/img/lasmid-profile.jpeg"
                      alt="profile-pics"
                      width={100}
                      height={100}
                      className="w-full h-full object-cover"
                    />
                  </div>
                </div>
                <div className="w-fit mx-auto flex gap-1 items-center">
                  <div className="text-sm font-bold text-black dark:text-white">Lasmid</div>
                </div>
                <div className="mt-2 flex justify-center">
                  <button
                    className="bg-green-500 text-white font-semibold py-2 px-4 rounded-full text-sm mx-auto">Follow</button>
                </div>
              </div>
              <div className="text-[9px] flex gap-1 items-center mt-2 pl-3 pr-2 text-gray-400 dark:text-gray-300">
                <FaUser className="self-start" />
                <p className="self-start">Don Jazzy and 39 others follow</p>
              </div>
            </div>

            <div className="w-32 h-52 bg-white dark:bg-[#3B3B3B] rounded-lg">
              <div className="px-6">
                <div className="flex items-center justify-center pt-4 pb-2">
                  <div className="w-20 h-20 rounded-full overflow-hidden">
                    <Image
                      src="/img/joeboy-profile.jpeg"
                      alt="profile-pics"
                      width={100}
                      height={100}
                      className="w-full h-full object-cover"
                    />
                  </div>
                </div>
                <div className="w-fit mx-auto flex gap-1 items-center">
                  <div className="text-sm font-bold text-black dark:text-white">Joeboy</div>
                  <span className="relative w-fit"><FaCertificate className="fa fa-certificate text-green-500 text-sm" />
                    <FaCheck className="fa fa-check absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2 text-[6px] font-extrabold text-white dark:text-[#3B3B3B]" />
                  </span>
                </div>
                <div className="mt-2 flex justify-center">
                  <button
                    className="bg-green-500 text-white font-semibold py-2 px-4 rounded-full text-sm mx-auto">Follow</button>
                </div>
              </div>
              <div className="text-[9px] flex gap-1 items-center mt-2 pl-3 pr-2 text-gray-400 dark:text-gray-300">
                <FaUser className="self-start" />
                <p className="self-start">Tiwa Savage and 72 others follow</p>
              </div>
            </div>
          </div>
        </div>

        <div className="post mt-4 px-2 md:px-6">
          <div className="w-full rounded-lg p-2 bg-white dark:bg-[#3B3B3B]">
            <div className="post-head flex justify-between">
              <div className="flex gap-2 cursor-pointer">
                <div className="flex items-center justify-center">
                  <div className="w-8 h-8 rounded-full overflow-hidden">
                    <Image
                      src="/img/omahlay-profile.jpeg"
                      alt="profile-pics"
                      width={100}
                      height={100}
                      className="w-full h-full object-cover"
                    />
                  </div>
                </div>
                <div>
                  <div className="flex gap-1 items-center">
                    <div className="text-xs font-bold text-black dark:text-white">Omah_lay</div>
                    <span className="relative w-fit"><FaCertificate className="fa fa-certificate text-green-500 text-sm" />
                      <FaCheck className="fa fa-check absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2 text-[6px] font-extrabold text-white dark:text-[#3B3B3B]" />
                    </span>
                  </div>
                  <div className="text-[8px] text-gray-400 dark:text-gray-300">LONDON, 13 MINUTES AGO</div>
                </div>
              </div>
              <div className="cursor-pointer text-black dark:text-white">
                <FaEllipsisH />
              </div>
            </div>

            <div className="post-img mt-[6px]">
              <div className="w-full h-44 rounded-lg overflow-hidden">
                <Image
                  src="/img/omahlay-post.jpg"
                  alt="post-img"
                  width={500}
                  height={500}
                  className="w-full h-full object-cover"
                />
              </div>
            </div>

            <div className="post-icons flex justify-between text-black dark:text-white mt-2 px-2">
              <div className="flex items-end gap-2">
                <FaRegHeart />
                <BiCommentDetail />
                <FaShareAlt />
              </div>
              <div>
                <FaRegBookmark />
              </div>
            </div>

            <div className="liked-by mt-2 flex gap-1 items-center">
              <div className="flex">
                <span>
                  <div className="flex items-center justify-center">
                    <div className="w-5 h-5 border-2 border-white rounded-full overflow-hidden dark:border-[#3B3B3B]">
                      <Image
                        src="/img/oxlade-profile.jpeg"
                        alt="profile-pics"
                        width={100}
                        height={100}
                        className="w-full h-full object-cover"
                      />
                    </div>
                  </div>
                </span>
                <span className="ml-[-0.6rem]">
                  <div className="flex items-center justify-center">
                    <div className="w-5 h-5 border-2 border-white rounded-full overflow-hidden dark:border-[#3B3B3B]">
                      <Image
                        src="/img/rema-profile.jpeg"
                        alt="profile-pics"
                        width={100}
                        height={100}
                        className="w-full h-full object-cover"
                      />
                    </div>
                  </div>
                </span>
                <span className="ml-[-0.6rem]">
                  <div className="flex items-center justify-center">
                    <div className="w-5 h-5 border-2 border-white rounded-full overflow-hidden dark:border-[#3B3B3B]">
                      <Image
                        src="/img/Jazzy-pics.jpg"
                        alt="profile-pics"
                        width={100}
                        height={100}
                        className="w-full h-full object-cover"
                      />
                    </div>
                  </div>
                </span>
              </div>
              <div>
                <p className="text-[10px] text-black dark:text-white">Liked by <span className="font-bold">Don Jazzy</span> and <span
                  className="font-bold">48,882 others</span></p>
              </div>
            </div>

            <div className="comments text-[10px]">
              <p className="text-black dark:text-white"><span className="font-bold">Omah_lay</span> Stream my new Song #Soso</p>
              <p className="text-gray-400 dark:text-gray-300">View all 1,039 comments</p>
            </div>
          </div>
        </div>

        <div className="post mt-4 px-2 md:px-6">
          <div className="w-full rounded-lg p-2 bg-white dark:bg-[#3B3B3B]">
            <div className="post-head flex justify-between">
              <div className="flex gap-2 cursor-pointer">
                <div className="flex items-center justify-center md:ml-1">
                  <div className="w-8 h-8 rounded-full overflow-hidden">
                    <Image
                      src="/img/ruger-profile.jpeg"
                      alt="profile-pics"
                      width={100}
                      height={100}
                      className="w-full h-full object-cover"
                    />
                  </div>
                </div>
                <div>
                  <div className="flex gap-1 items-center">
                    <div className="text-xs font-bold text-black dark:text-white">Ruger</div>
                    <span className="relative w-fit"><FaCertificate className="fa fa-certificate text-green-500 text-sm" />
                      <FaCheck className="fa fa-check absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2 text-[6px] font-extrabold text-white dark:text-[#3B3B3B]" />
                    </span>
                  </div>
                  <div className="text-[8px] text-gray-400 dark:text-gray-300">PARIS, 5 MINUTES AGO</div>
                </div>
              </div>
              <div className="cursor-pointer text-black dark:text-white">
                <FaEllipsisH />
              </div>
            </div>

            <div className="post-img mt-[6px]">
              <div className="w-full h-44 rounded-lg overflow-hidden">
                <Image
                  src="/img/ruger-post2.jpeg"
                  alt="post-img"
                  width={500}
                  height={500}
                  className="w-full h-full object-cover"
                />
              </div>
            </div>

            <div className="post-icons flex justify-between text-black dark:text-white mt-2 px-2">
              <div className="flex items-end gap-2">
                <FaRegHeart />
                <BiCommentDetail />
                <FaShareAlt />
              </div>
              <div>
                <FaRegBookmark />
              </div>
            </div>

            <div className="liked-by mt-2 flex gap-1 items-center">
              <div className="flex">
                <span>
                  <div className="flex items-center justify-center">
                    <div className="w-5 h-5 border-2 border-white rounded-full overflow-hidden dark:border-[#3B3B3B]">
                      <Image
                        src="/img/rema-profile.jpeg"
                        alt="profile-pics"
                        width={100}
                        height={100}
                        className="w-full h-full object-cover"
                      />
                    </div>
                  </div>
                </span>
                <span className="ml-[-0.6rem]">
                  <div className="flex items-center justify-center">
                    <div className="w-5 h-5 border-2 border-white rounded-full overflow-hidden dark:border-[#3B3B3B]">
                      <Image
                        src="/img/star-profile.jpeg"
                        alt="profile-pics"
                        width={100}
                        height={100}
                        className="w-full h-full object-cover"
                      />
                    </div>
                  </div>
                </span>
                <span className="ml-[-0.6rem]">
                  <div className="flex items-center justify-center">
                    <div className="w-5 h-5 border-2 border-white rounded-full overflow-hidden dark:border-[#3B3B3B]">
                      <Image
                        src="/img/dprince-pics.jpg"
                        alt="profile-pics"
                        width={100}
                        height={100}
                        className="w-full h-full object-cover"
                      />
                    </div>
                  </div>
                </span>
              </div>
              <div>
                <p className="text-[10px] text-black dark:text-white">Liked by <span className="font-bold">D Prince</span> and <span
                  className="font-bold">69,294 others</span></p>
              </div>
            </div>

            <div className="comments text-[10px]">
              <p className="text-black dark:text-white"><span className="font-bold">Ruger</span> We outside #RuTheWorld</p>
              <p className="text-gray-400 dark:text-gray-300">View all 7,125 comments</p>
            </div>
          </div>
        </div>

        <div className="h-11 w-11 bg-green-500 rounded-full grid place-content-center fixed md:hidden bottom-7 left-6 text-white dark:text-[#070707]"><FaPlus /></div>
        <div className="h-11 w-11 bg-green-500 rounded-full hidden md:block md:sticky md:bottom-10 md:ml-20 text-white dark:text-[#070707]"><div className="w-full h-full grid place-content-center"><FaPlus /></div></div>
      </div>

      <div className="hidden lg:block lg:w-[25%] lg:h-screen"></div>
    </main>
  )
}