import { FaSearch } from "react-icons/fa";
import { MdEdit } from "react-icons/md";
import { FaCertificate } from "react-icons/fa";
import { FaCheck } from "react-icons/fa";
import Image from "next/image";
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Message',
  description: 'Generated by create next app',
}

export default function Message() {
  return (
    <div className="flex items-center">

      <div className="hidden md:block md:w-1/3 md:h-screen lg:w-[25%]"></div>

      <div className="mt-[60px] md:mt-[68px] px-2 pt-4 w-full md:w-2/3 lg:w-[50%]">
        <div className="searchbar md:px-16">
          <form>
            <div className="relative flex items-center text-gray-400 focus-within:text-gray-700">
              <FaSearch className="absolute ml-3 pointer-events-none" />
              <input type="text" name="search" placeholder="Search..." autoComplete="off" aria-label="Search..."
                className="w-full pr-3 pl-10 py-2 font-semibold text-black rounded-full outline-green-500" />
            </div>
          </form>
        </div>

        <div className="starred mt-2 md:px-6">
          <div className="flex justify-between items-center text-green-500 pr-2">
            <div className="font-bold pl-2">Starred</div>
            <div className="text-xs">1 unread messages</div>
          </div>
          <div className="bg-white dark:bg-[#3B3B3B] rounded-2xl mt-2">
            <div className="flex gap-2 items-center p-2">
              <div className="relative">
                <div className="w-10 h-10 rounded-full overflow-hidden">
                  <Image
                    src="/img/oxlade-profile.jpeg"
                    alt="profile-pics"
                    width={100}
                    height={100}
                    className="w-full h-full object-cover"
                  />
                </div>
                <div
                  className="w-2 h-2 rounded-full absolute bottom-0 right-0 bg-blue-500 box-content border-2 border-solid border-white dark:border-[#3B3B3B]">
                </div>
              </div>
              <div className="flex justify-between w-full items-center pb-1 border-b border-gray-400 border-solid dark:border-gray-500">
                <div>
                  <div className="flex gap-1 items-center">
                    <div className="text-xs font-bold text-black dark:text-white">Oxlade</div>
                    <span className="relative w-fit"><FaCertificate className="fa fa-certificate text-green-500 text-sm" />
                      <FaCheck className="fa fa-check absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2 text-[6px] font-extrabold text-white dark:text-[#3B3B3B]" />
                    </span>
                  </div>
                  <div className="text-[10px] text-gray-400 dark:text-gray-300">Send me the verse for the song! Abeg</div>
                </div>
                <div className="text-xs text-black dark:text-white">Now</div>
              </div>
            </div>

            <div className="flex gap-2 items-center px-2 pb-2">
              <div>
                <div className="w-10 h-10 rounded-full overflow-hidden">
                  <Image
                    src="/img/rema-profile.jpeg"
                    alt="profile-pics"
                    width={100}
                    height={100}
                    className="w-full h-full object-cover"
                  />
                </div>
              </div>
              <div className="flex justify-between w-full items-center pb-1 border-b border-gray-400 border-solid dark:border-gray-500">
                <div>
                  <div className="flex gap-1 items-center">
                    <div className="text-xs font-bold text-black dark:text-white">Rema</div>
                    <span className="relative w-fit"><FaCertificate className="fa fa-certificate text-green-500 text-sm" />
                      <FaCheck className="fa fa-check absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2 text-[6px] font-extrabold text-white dark:text-[#3B3B3B]" />
                    </span>
                  </div>
                  <div className="text-[10px] text-gray-400 dark:text-gray-300">Please are with my charger?</div>
                </div>
                <div className="text-xs text-black dark:text-white">10 mins</div>
              </div>
            </div>

            <div className="flex gap-2 items-center px-2 pb-2">
              <div>
                <div className="w-10 h-10 rounded-full overflow-hidden">
                  <Image
                    src="/img/Jazzy-pics.jpg"
                    alt="profile-pics"
                    width={100}
                    height={100}
                    className="w-full h-full object-cover"
                  />
                </div>
              </div>
              <div className="flex justify-between w-full items-center pb-1">
                <div>
                  <div className="flex gap-1 items-center">
                    <div className="text-xs font-bold text-black dark:text-white">Don Jazzy</div>
                    <span className="relative w-fit"><FaCertificate className="fa fa-certificate text-green-500 text-sm" />
                      <FaCheck className="fa fa-check absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2 text-[6px] font-extrabold text-white dark:text-[#3B3B3B]" />
                    </span>
                  </div>
                  <div className="text-[10px] text-gray-400 dark:text-gray-300">Have you recorded the song?</div>
                </div>
                <div className="text-xs text-black dark:text-white">1 hour</div>
              </div>
            </div>
          </div>
        </div>

        <div className="message mt-2 pb-2 md:px-6">
          <div className="flex justify-between items-center text-green-500 pr-2">
            <div className="font-bold pl-2">Message</div>
            <div className="text-xs">3 unread messages</div>
          </div>
          <div className="bg-white dark:bg-[#3B3B3B] rounded-2xl mt-2 pb-2">
            <div className="flex gap-2 items-center p-2">
              <div>
                <div className="w-10 h-10 rounded-full overflow-hidden">
                  <Image
                    src="/img/ruger-profile.jpeg"
                    alt="profile-pics"
                    width={100}
                    height={100}
                    className="w-full h-full object-cover"
                  />
                </div>
              </div>
              <div className="flex justify-between w-full items-center pb-1 border-b border-gray-400 border-solid dark:border-gray-500">
                <div>
                  <div className="flex gap-1 items-center">
                    <div className="text-xs font-bold text-black dark:text-white">Ruger</div>
                    <span className="relative w-fit"><FaCertificate className="fa fa-certificate text-green-500 text-sm" />
                      <FaCheck className="fa fa-check absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2 text-[6px] font-extrabold text-white dark:text-[#3B3B3B]" />
                    </span>
                  </div>
                  <div className="text-[10px] text-gray-400 dark:text-gray-300">Can we link up?</div>
                </div>
                <div className="text-xs text-black dark:text-white">52 mins</div>
              </div>
            </div>

            <div className="flex gap-2 items-center px-2 pb-2">
              <div className="relative">
                <div className="w-10 h-10 rounded-full overflow-hidden">
                  <Image
                    src="/img/fireboy-profile.jpeg"
                    alt="profile-pics"
                    width={100}
                    height={100}
                    className="w-full h-full object-cover"
                  />
                </div>
                <div
                  className="w-2 h-2 rounded-full absolute bottom-0 right-0 bg-blue-500 box-content border-2 border-solid border-white dark:border-[#3B3B3B]">
                </div>
              </div>
              <div className="flex justify-between w-full items-center pb-1 border-b border-gray-400 border-solid dark:border-gray-500">
                <div>
                  <div className="flex gap-1 items-center">
                    <div className="text-xs font-bold text-black dark:text-white">Fireboy</div>
                    <span className="relative w-fit"><FaCertificate className="fa fa-certificate text-green-500 text-sm" />
                      <FaCheck className="fa fa-check absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2 text-[6px] font-extrabold text-white dark:text-[#3B3B3B]" />
                    </span>
                  </div>
                  <div className="text-[10px] text-gray-400 dark:text-gray-300">See you at the party</div>
                </div>
                <div className="text-xs text-black dark:text-white">12:07pm</div>
              </div>
            </div>

            <div className="flex gap-2 items-center px-2 pb-2">
              <div className="relative">
                <div className="w-10 h-10 rounded-full overflow-hidden">
                  <Image
                    src="/img/mayorkun-profile.jpeg"
                    alt="profile-pics"
                    width={100}
                    height={100}
                    className="w-full h-full object-cover"
                  />
                </div>
                <div
                  className="w-2 h-2 rounded-full absolute bottom-0 right-0 bg-blue-500 box-content border-2 border-solid border-white dark:border-[#3B3B3B]">
                </div>
              </div>
              <div className="flex justify-between w-full items-center pb-1 border-b border-gray-400 border-solid dark:border-gray-500">
                <div>
                  <div className="flex gap-1 items-center">
                    <div className="text-xs font-bold text-black dark:text-white">Mayorkun</div>
                    <span className="relative w-fit"><FaCertificate className="fa fa-certificate text-green-500 text-sm" />
                      <FaCheck className="fa fa-check absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2 text-[6px] font-extrabold text-white dark:text-[#3B3B3B]" />
                    </span>
                  </div>
                  <div className="text-[10px] text-gray-400 dark:text-gray-300">Please follow me</div>
                </div>
                <div className="text-xs text-black dark:text-white">10:29am</div>
              </div>
            </div>

            <div className="flex gap-2 items-center px-2 pb-2">
              <div>
                <div className="w-10 h-10 rounded-full overflow-hidden">
                  <Image
                    src="/img/omahlay-profile.jpeg"
                    alt="profile-pics"
                    width={100}
                    height={100}
                    className="w-full h-full object-cover"
                  />
                </div>
              </div>
              <div className="flex justify-between w-full items-center pb-1 border-b border-gray-400 border-solid dark:border-gray-500">
                <div>
                  <div className="flex gap-1 items-center">
                    <div className="text-xs font-bold text-black dark:text-white">Omah_lay</div>
                    <span className="relative w-fit"><FaCertificate className="fa fa-certificate text-green-500 text-sm" />
                      <FaCheck className="fa fa-check absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2 text-[6px] font-extrabold text-white dark:text-[#3B3B3B]" />
                    </span>
                  </div>
                  <div className="text-[10px] text-gray-400 dark:text-gray-300">How are you doing?</div>
                </div>
                <div className="text-xs text-black dark:text-white">8:41am</div>
              </div>
            </div>

            <div className="flex gap-2 items-center px-2 pb-2">
              <div className="relative">
                <div className="w-10 h-10 rounded-full overflow-hidden">
                  <Image
                    src="/img/joeboy-profile.jpeg"
                    alt="profile-pics"
                    width={100}
                    height={100}
                    className="w-full h-full object-cover"
                  />
                </div>
                <div
                  className="w-2 h-2 rounded-full absolute bottom-0 right-0 bg-blue-500 box-content border-2 border-solid border-white dark:border-[#3B3B3B]">
                </div>
              </div>
              <div className="flex justify-between w-full items-center pb-1 border-b border-gray-400 border-solid dark:border-gray-500">
                <div>
                  <div className="flex gap-1 items-center">
                    <div className="text-xs font-bold text-black dark:text-white">Joeboy</div>
                    <span className="relative w-fit"><FaCertificate className="fa fa-certificate text-green-500 text-sm" />
                      <FaCheck className="fa fa-check absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2 text-[6px] font-extrabold text-white dark:text-[#3B3B3B]" />
                    </span>
                  </div>
                  <div className="text-[10px] text-gray-400 dark:text-gray-300">Good morning</div>
                </div>
                <div className="text-xs text-black dark:text-white">7:34am</div>
              </div>
            </div>

            <div className="flex gap-2 items-center px-2">
              <div>
                <div className="w-10 h-10 rounded-full overflow-hidden">
                  <Image
                    src="/img/lasmid-profile.jpeg"
                    alt="profile-pics"
                    width={100}
                    height={100}
                    className="w-full h-full object-cover"
                  />
                </div>
              </div>
              <div className="flex justify-between w-full items-center pb-1">
                <div>
                  <div className="text-xs font-bold text-black dark:text-white">Lasmid</div>
                  <div className="text-[10px] text-gray-400 dark:text-gray-300">Please can you jump on the remix of my song &apos;Bad boy&apos;?</div>
                </div>
                <div className="text-xs text-black dark:text-white">Yesterday</div>
              </div>
            </div>
          </div>
        </div>

        <div className="h-11 w-11 bg-green-500 rounded-full grid place-content-center fixed md:hidden bottom-7 left-6 text-white dark:text-[#070707]"><MdEdit /></div>
        <div className="h-11 w-11 bg-green-500 rounded-full hidden md:block md:sticky md:bottom-10 md:ml-20 text-white dark:text-[#070707]"><div className="w-full h-full grid place-content-center"><MdEdit /></div></div>
      </div>

      <div className="hidden lg:block lg:w-[25%] lg:h-screen"></div>
    </div>
  )
}