import { FiMapPin } from "react-icons/fi";
import { MdOutlineMail } from "react-icons/md";
import { HiLink } from "react-icons/hi";
import { FaCertificate } from "react-icons/fa";
import { FaCheck } from "react-icons/fa";
import DashboardNavbar from "../../components/DashboardNavbar";
import Image from "next/image";
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
}

export default function Dashboard() {
  return (
    <div>
      <DashboardNavbar />

      <div className="flex items-center">

        <div className="hidden md:block md:w-1/3 md:h-screen lg:w-[25%]"></div>

        <div className="w-full h-screen md:w-2/3 lg:w-[50%] md:border-l md:border-solid md:border-gray-400 dark:md:border-gray-500 lg:border-r lg:border-solid lg:border-gray-400 dark:lg:border-gray-500">
          <div className="h-screen w-full pt-[60px] md:px-6 overflow-y-auto bg-white dark:bg-[#3B3B3B]">
            <div className="pt-3 lg:pt-12">
              <div className="flex items-center justify-center">
                <div className="w-14 h-14 border-2 border-green-500 rounded-full overflow-hidden">
                  <Image
                    src="/img/star-profile.jpeg"
                    alt="profile-pics"
                    width={100}
                    height={100}
                    className="w-full h-full object-cover"
                  />
                </div>
              </div>
            </div>
            <div className="flex gap-1 items-center justify-center my-2 lg:mt-1">
              <div className="text-sm font-bold text-green-500">Ayra Star</div>
              <span className="relative w-fit"><FaCertificate className="fa fa-certificate text-green-500 text-sm" />
                <FaCheck className="fa fa-check absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2 text-[6px] font-extrabold text-white dark:text-[#3B3B3B]" />
              </span>
            </div>
            <div className="flex justify-evenly items-center mt-0 text-center">
              <div>
                <div className="text-sm font-bold text-green-500">0</div>
                <div className="text-[10px] text-black dark:text-white">Posts</div>
              </div>
              <div>
                <div className="text-sm font-bold text-green-500">4.1M</div>
                <div className="text-[10px] text-black dark:text-white">Followers</div>
              </div>
              <div>
                <div className="text-sm font-bold text-green-500">1,212</div>
                <div className="text-[10px] text-black dark:text-white">Following</div>
              </div>
            </div>
            <div className="text-sm font-bold text-green-500 mt-2 text-center lg:mt-4">INTRO</div>
            <div className="px-4 text-center text-xs">
              <p className="pb-2 border-b border-gray-400 dark:border-gray-500 border-solid text-black dark:text-white">Celestial being</p>
            </div>
            <div className="mt-2 text-black dark:text-white text-sm pl-3 lg:mt-4">
              <div>
                <div className="flex gap-2 items-center">
                  <div className="w-6 h-6 flex items-center">
                    <FiMapPin className="mr-2 font-extrabold" />
                  </div>
                  <div>
                    <span>Banana island, lagos Nigeria</span>
                  </div>
                </div>
              </div>

              <div>
                <div className="flex gap-2 items-center">
                  <div className="w-6 h-6 flex items-center">
                    <MdOutlineMail className="mr-2 font-extrabold" />
                  </div>
                  <div>
                    <span>ayrastarr@marvinrecords.com</span>
                  </div>
                </div>
              </div>

              <div>
                <div className="flex gap-2 items-center">
                  <div className="w-6 h-6 flex items-center">
                    <HiLink className="mr-2 font-extrabold" />
                  </div>
                  <div>
                    <span>ayrastarr.com</span>
                  </div>
                </div>
              </div>
            </div>
            <div className="mt-4 flex items-center justify-around text-black dark:text-white border-b border-t border-gray-400 dark:border-gray-500 border-solid">
              <div className="py-2 border-b-2 border-green-500 border-solid">Posts</div>
              <div className="py-2">Replies</div>
              <div className="py-2">Media</div>
              <div className="py-2">Likes</div>
            </div>
            <div className="mt-20 mb-20 grid place-content-center text-2xl text-green-500 font-agbalumo">No Posts Yet</div>
          </div>
        </div>

        <div className="hidden lg:block lg:w-[25%] lg:h-screen"></div>
      </div>
    </div>
  )
}